### ISSUE TITLE
Feature request: Add complete auto discovery to MQTT

### ISSUE THREAD

**Issue by Eyal51** [technyon/nuki_hub#170]
Add complete auto discovery for keypad 2.0 so information such as who opened the door or actions such as disabling a code will be available

**Comment by technyon** [comment]
Due to the way the bluetooth API is implemented, such features are difficult to implement. Only the last 5 log entries are available on MQTT side, and from this the auto discovery has to guess what happened. Disabling a code isn't logged at all, so there's no way this can be put into auto-discovery.

For NUKI Hub, there's no difference between Keypad 1.0 and 2.0 (just for the record).
