### ISSUE TITLE
Feature request: report intermediate lock states (locking, unlocking, jammed)

### ISSUE THREAD

**Issue by desheh** [technyon/nuki_hub#181]
As the [MQTT Lock API ](https://www.home-assistant.io/integrations/lock.mqtt/) supports it, it could be nice if the nuki hub could also publish the [locking, unlocking] states (so a click on lock/unlock in HA will show that it's actually doing something).

![229340330-c12a76b5-6d96-4f5b-b171-466a223728be](https://user-images.githubusercontent.com/5565392/235260056-de7eb1bc-8276-4eb9-8864-ec95b92520c8.png)

**Comment by technyon** [comment]
NUKI Hub already reports those states ... or at least it has the capability to do that. States like locking and unlocking often aren't reported because they only last for a short amount of time. The lock tells the ESP that the state has changed via ble beacons, which causes NUKI Hub to query the ne state, which can take a few seconds. Often the next state (e. g. locked after unlocking) has already been reached, so you don't see the intermediate state.
