### ISSUE TITLE
Feature Request - HTTP/HTTPS REST Interface

### ISSUE THREAD

**Issue by patrickmarchhart** [technyon/nuki_hub#186]
Is there a possibility to control the Nuki Hub via HTTP or HTTPS commands?

**Comment by patrickmarchhart** [comment]
I would like to integrate the Nuki Hub into a Loxone automation system.

**Comment by technyon** [comment]
To give you an answer, such feature isn't impossible, but it's a considerable amount of work. It's not only implementation, but also designing an API and testing if the API works as intended. I've chosen MQTT as a protocol because it's quite easy to use and something that's supported by most IOT solutions, REST certainly needs more experience to use it.

As far as I've seen, there are ways to integrate MQTT into Loxone, which is I think easier and faster than integrating a REST API. So no, I'm not planning to add a REST API at this time.
