### ISSUE TITLE
Auto unlatch on startup ... use nuki hub as fob

### ISSUE THREAD

**Issue by root-intruder** [technyon/nuki_hub#237]
Hi,
first of all, thank you for this awesome project!

I want to misuse nuki hub as a fob. That means, I want to power up the ESP via a button and directly send an unlatch signal to the paired nuki lock. 
In order to get this working, I configured pin 23 as Input: Unlatch and wired pin 23 pysically to ground. However, when I boot the esp, no unlatch is triggered. However, if I put a button in between which I push when esp booted up, it works fine, but I don't want to push 2 buttons.

Any Ideas how to solve this or why the esp doesn't register the constant pull down to ground for GPIO Input unlatch?

Thanks!

**Comment by technyon** [comment]
Hi,

the reason for this is very simple: This firmware registers an event that is to be triggered when the input of the GPIO PIN changes. If you just connect the PIN to ground, it's already at low state when it has finished booting. Since no further change on the input occurs, no lock action is triggered.

I think a much simpler firmware would do for you. It should put the ESP into deep sleep, wake up on button press, trigger the lock action, and go back to deep sleep after booting.
