### ISSUE TITLE
(Question) Are key fobs compatible?

### ISSUE THREAD

**Issue by anthonws** [technyon/nuki_hub#260]
Are key fobs compatible with nuki_hub? Anything special that would be required or what are the limitations that don't allow them to be supported (if that is the case)?
What other options have you chosen as alternative? Keypad?

**Comment by technyon** [comment]
You pair the fobs with the lock and not NUKI Hub, in that sense they are compatible.

But if you're asking if you can pair the Fobs with NUKI Hub and get notified about key presses, the answer is no. NUKI Hub is working as a client that connects to the lock. To make it work with Fobs like that, it would need to simulate a lock, because the Fobs expect a lock to be paired with.

The same goes for the keypad, except the NUKI Hub allow to add and remove keypad codes. It does so however by talking to the lock, not to the keypad directly ... which makes a lot of sense because the codes are stored on the lock due to security concerns.
